# Generated by Django 6.1 on 2026-09-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_english_interface_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=80)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('frame_hashes', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'device_id'), name='uniq_recognition_device_session')],
            },
        ),
    ]
