# Generated by Django 6.1 on 2026-09-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_attendance_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
            ],
            options={
                'ordering': ['-starts_on', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='valid_academic_term_dates')],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.academicterm', verbose_name='Semester'),
        ),
    ]
