# Generated by Django 6.1 on 2026-09-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_academicterm_schedule_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='AcademicPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_demo', models.BooleanField(default=True)),
                ('pass_score', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('min_scholarship_average', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('min_scholarship_credits', models.PositiveSmallIntegerField(default=12)),
                ('min_conduct_score', models.PositiveSmallIntegerField(default=80)),
                ('graduation_credits', models.PositiveSmallIntegerField(default=120)),
                ('min_graduation_average', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('max_term_credits', models.PositiveSmallIntegerField(default=24)),
                ('require_english', models.BooleanField(default=True)),
                ('require_physical_education', models.BooleanField(default=True)),
                ('require_defense', models.BooleanField(default=True)),
                ('require_financial_clearance', models.BooleanField(default=True)),
                ('required_subjects', models.ManyToManyField(blank=True, to='portal.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=0, editable=False)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for_offerings', to='portal.subject')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offering', to='portal.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='portal.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_certified', models.BooleanField(blank=True, null=True)),
                ('physical_education_completed', models.BooleanField(blank=True, null=True)),
                ('defense_completed', models.BooleanField(blank=True, null=True)),
                ('financial_clearance', models.BooleanField(blank=True, null=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.academicpolicy')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='TermAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='academicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('min_conduct_score__lte', 100), ('min_graduation_average__gte', 0), ('min_graduation_average__lte', 10), ('min_scholarship_average__gte', 0), ('min_scholarship_average__lte', 10), ('pass_score__gte', 0), ('pass_score__lte', 10)), name='valid_academic_policy_scores'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('closes_on__gte', models.F('opens_on'))), name='valid_registration_window'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='positive_offering_capacity'),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(fields=('student', 'offering'), name='unique_student_offering'),
        ),
        migrations.AddConstraint(
            model_name='termassessment',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='unique_student_term_assessment'),
        ),
        migrations.AddConstraint(
            model_name='termassessment',
            constraint=models.CheckConstraint(condition=models.Q(('conduct_score__lte', 100), ('conduct_score__isnull', True), _connector='OR'), name='valid_conduct_score'),
        ),
    ]
