# Generated by Django 6.1 on 2026-09-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_subject_teacher_bio_subject_teacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bonus_method',
            field=models.CharField(default='DIRECT', max_length=20, verbose_name='Bonus Method'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weight_cc',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4, verbose_name='Attendance Weight'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weight_ck',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4, verbose_name='Final Weight'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weight_gk',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='Midterm Weight'),
        ),
    ]
