# Generated by Django 6.1 on 2026-09-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_subject_bonus_method_subject_weight_cc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Password hash'),
        ),
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('before_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('after_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='portal.grade')),
            ],
            options={
                'verbose_name': 'Grade audit log',
                'verbose_name_plural': 'Grade audit logs',
                'ordering': ['-changed_at', '-pk'],
            },
        ),
    ]
